server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagement?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: Academy4root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 900





  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 275713030630-l72br4mumnilcbjjgpuli8a9josnfvkb.apps.googleusercontent.com
            client-secret: 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


logging:
  level:
    org:
      hibernate:
        SQL: debug

